AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type
  SubnetId:
    Type: String
    Default: <Subnet Id>
    AllowedValues:
    # example > subnet-0c16a666a463c1234
    - <Subnet Id>
    - <Subnet Id>
    - <Subnet Id>
    - <Subnet Id>
    ConstraintDescription: must be a valid SbunetID


Mappings:
  RegionMap:
    # https://aws.amazon.com/jp/amazon-linux-ami/
    # hvm ebs 64bit
    ap-northeast-1:
      hvm: "ami-06cd52961ce9f0d85" # For Tokyo
    ap-southeast-1:
      hvm: "ami-08569b978cc4dfa10" # For Singapore


Description: Create EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', hvm]
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            # unit > GB
            VolumeSize: 8
      Tags:
      - Key: Name
        Value: myInstance
