AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06cd52961ce9f0d85 # https://aws.amazon.com/jp/amazon-linux-ami/
      InstanceType: t2.micro
